services:
  - type: web
    name: openai-api-proxy
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false
        type: secret
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1